import React from "react";

const c = () => (
  <div style={{ padding: 24, background: "#fff", textAlign: "center" }}>
    ...
    <br />
    Really
    <br />...<br />...<br />...<br />
    long
    <br />...<br />...<br />...<br />...<br />...<br />...
    <br />...<br />...<br />...<br />...<br />...<br />...
    <br />...<br />...<br />...<br />...<br />...<br />...
    <br />...<br />...<br />...<br />
    long
    <br />...<br />...<br />...<br />...<br />...<br />...
    <br />...<br />...<br />...<br />...<br />...<br />...
    <br />...<br />...<br />...<br />...<br />...<br />...
    <br />...<br />...<br />...<br />...<br />...<br />...
    <br />...<br />...<br />...<br />
    long
    <br />...<br />...<br />...<br />...<br />...<br />...
    <br />...<br />...<br />...<br />...<br />...<br />...
    <br />...<br />...<br />...<br />...<br />...<br />...
    <br />...<br />...<br />...<br />...<br />...<br />...
    <br />...<br />...<br />...<br />...<br />...<br />...
    <br />...<br />...<br />...<br />...<br />...<br />
    content
  </div>
);

export default c;
